In [8]:
import numpy as np

In [4]:
def textEnumErrorMsg(var, valids):
    if type(valids[0])==str:
        return "Invalid '%s'! (It must be one of %s)"%(var, ", ".join(["'%s'"%(str(x)) for x in valids[:-1]]) + ", or '%s'"%(str(valids[-1])))
    return "Invalid '%s'! (It must be one of %s)"%(var, ", ".join(["%s"%(str(x)) for x in valids[:-1]]) + ", or %s"%(str(valids[-1])))


In [78]:
def enumErrorMsg(var, valids):
    if type(valids)==list:
        formatStr = "'%s'" if type(valids[0])==str else "%s"
        return "Invalid '%s'! ('%s' ∈ {%s})"%(var, var, ", ".join([formatStr%str(x) for x in valids]))
    
    if type(valids)==tuple and len(valids)==2:
        formatStr = "'%s'" if type(valids[0])==str else "%s"
        return "Invalid '%s'! ('%s' ∈ {%s})"%(var, var, ",...,".join([formatStr%str(x) for x in valids]))
    
    formatStr = "'%s'" if type(valids)==str else "%s"
    return "Invalid '%s'! (It must be "%(var) + formatStr%str(valids) + ")"

def validateRange(var, valids, context="", varName=None):
    if varName is None:
        import inspect
        frame = inspect.getouterframes(inspect.currentframe())[1]
        string = inspect.getframeinfo(frame[0]).code_context[0].strip()
        varName = string[string.find('(') + 1:-1].split(',')[0].strip("self.")

    if type(valids)==list:
        if var in valids:                      return
        fStr = "'%s'" if type(valids[0])==str else "%s"
        raise ValueError("Invalid '%s'! ('%s' ∈ {%s}%s)"%(varName, varName,
                                                        ", ".join([fStr%str(x) for x in valids]), context))

    if type(valids)==tuple and len(valids)==2:
        if var in range(valids[0],valids[1]+1): return
        fStr = "'%s'" if type(valids[0])==str else "%s"
        raise ValueError("Invalid '%s'! ('%s' ∈ {%s}%s)"%(varName, varName,
                                                        ",...,".join([fStr%str(x) for x in valids]), context))

    if var==valids:                              return
    fStr = "'%s'" if type(valids)==str else "%s"
    raise ValueError("Invalid '%s'! (It must be "%(varName) + fStr%str(valids) + context + ")")


In [90]:
from scipy.special import comb
comb(14, 3)

364.0

In [81]:
class cl:
    def __init__(self):
        self.a = 122
        validateRange(self.a, (1,10), " when my context")

b = cl()

        

ValueError: Invalid 'a'! ('a' ∈ {1,...,10} when my context)

In [46]:
a123 = 123
def f(var):
    frame = inspect.getouterframes(inspect.currentframe())[1]
    string = inspect.getframeinfo(frame[0]).code_context[0].strip()
    varName = string[string.find('(') + 1:-1].split(',')[0]
    print(varName)

f(a123)

a123


In [29]:
enumErrorMsg("par", "(12,1,3)")

"Invalid 'par'! (It must be '(12,1,3)')"

In [36]:
enumErrorMsg("par", [1,2,3,4]), enumErrorMsg("par", (1,4)), enumErrorMsg("par", "shahab")

("Invalid 'par'! ('par' ∈ {1, 2, 3, 4})",
 "Invalid 'par'! ('par' ∈ {1,...,4})",
 "Invalid 'par'! (It must be 3)")

In [30]:
codebooks = np.array([ [[1], [1]], [[1], [1j]], [[1], [-1]], [[1], [-1j]] ])/np.sqrt(2)
codebooks.shape, codebook

((4, 2, 1),
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        +0.70710678j],
        [ 0.70710678+0.j        , -0.70710678+0.j        ],
        [ 0.70710678+0.j        , -0.        -0.70710678j]]))

In [15]:
codebooks[1] = [[0],[0]]
codebooks

array([[[ 0.70710678+0.j        ],
        [ 0.70710678+0.j        ]],

       [[ 0.        +0.j        ],
        [ 0.        +0.j        ]],

       [[ 0.70710678+0.j        ],
        [-0.70710678+0.j        ]],

       [[ 0.70710678+0.j        ],
        [-0.        -0.70710678j]]])

In [14]:
codebooks

array([[[ 0.70710678+0.j        ],
        [ 0.70710678+0.j        ]],

       [[ 0.70710678+0.j        ],
        [ 0.        +0.70710678j]],

       [[ 0.70710678+0.j        ],
        [-0.70710678+0.j        ]],

       [[ 0.70710678+0.j        ],
        [-0.        -0.70710678j]]])

In [29]:
codebooks = np.array([ [[1, 1], [1, -1]], [[1, 1], [1j, -1j]] ])/2
codebooks.shape, codebook

((2, 2, 2),
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        +0.70710678j],
        [ 0.70710678+0.j        , -0.70710678+0.j        ],
        [ 0.70710678+0.j        , -0.        -0.70710678j]]))

In [26]:
codebooksAllowed = "110101"
codebooks = np.array([ [[1], [1]], [[1], [1j]], [[1], [-1]], [[1], [-1j]] ])/np.sqrt(2)
for i in range(4):
    if codebooksAllowed[-i-1]=='0':  # Codebook i is restricted
        codebooks[i] = 0
codebooks

array([[[ 0.70710678+0.j],
        [ 0.70710678+0.j]],

       [[ 0.        +0.j],
        [ 0.        +0.j]],

       [[ 0.70710678+0.j],
        [-0.70710678+0.j]],

       [[ 0.        +0.j],
        [ 0.        +0.j]]])

In [28]:
codebooksAllowed = "010101"
codebooks = np.array([ [[1, 1], [1, -1]], [[1, 1], [1j, -1j]] ])/2
for i in [4,5]:
    if codebooksAllowed[-i-1]=='0':  # Codebook i is restricted
        codebooks[i-4] = 0
codebooks


array([[[ 0.5+0.j,  0.5+0.j],
        [ 0.5+0.j, -0.5+0.j]],

       [[ 0. +0.j,  0. +0.j],
        [ 0. +0.j,  0. +0.j]]])

In [38]:
a = [1,2]
b = [3,4,5]
uum = np.int32([[2,3],[4,5],[6,7]])
uul = np.int32([[5,6,7],[5,6,7],[5,6,7],[5,6,7]])
# np.outer(uul, uum)

In [54]:
a = [1,2,3,4,5]
b = [3,4,5,6]
ab = np.outer(a, b)
ab.shape, ab

((5, 4),
 array([[ 3,  4,  5,  6],
        [ 6,  8, 10, 12],
        [ 9, 12, 15, 18],
        [12, 16, 20, 24],
        [15, 20, 25, 30]]))

In [55]:
c= [6,7,8]
d = [9,10,11,12]
cd = np.outer(c, d)
cd.shape, cd

((3, 4),
 array([[54, 60, 66, 72],
        [63, 70, 77, 84],
        [72, 80, 88, 96]]))

In [57]:
x = np.outer(ab, cd).reshape(5,4,3,4)
x.shape, x

((5, 4, 3, 4),
 array([[[[ 162,  180,  198,  216],
          [ 189,  210,  231,  252],
          [ 216,  240,  264,  288]],
 
         [[ 216,  240,  264,  288],
          [ 252,  280,  308,  336],
          [ 288,  320,  352,  384]],
 
         [[ 270,  300,  330,  360],
          [ 315,  350,  385,  420],
          [ 360,  400,  440,  480]],
 
         [[ 324,  360,  396,  432],
          [ 378,  420,  462,  504],
          [ 432,  480,  528,  576]]],
 
 
        [[[ 324,  360,  396,  432],
          [ 378,  420,  462,  504],
          [ 432,  480,  528,  576]],
 
         [[ 432,  480,  528,  576],
          [ 504,  560,  616,  672],
          [ 576,  640,  704,  768]],
 
         [[ 540,  600,  660,  720],
          [ 630,  700,  770,  840],
          [ 720,  800,  880,  960]],
 
         [[ 648,  720,  792,  864],
          [ 756,  840,  924, 1008],
          [ 864,  960, 1056, 1152]]],
 
 
        [[[ 486,  540,  594,  648],
          [ 567,  630,  693,  756],
          [ 648,  7

In [70]:
vml = np.arange(24).reshape(2,3,4)
phi = np.arange(5)
vml,phi

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([0, 1, 2, 3, 4]))

In [88]:
vmlPhi = np.outer(phi,vml).reshape(5,2,3,4)
vmlPhi.shape

(5, 2, 3, 4)

In [97]:
cb = np.concatenate([5*[vml], vmlPhi], axis=-1)
cb.shape

(5, 2, 3, 8)

In [96]:
cb[1,1,1]

array([16, 17, 18, 19, 16, 17, 18, 19])

In [98]:
cb.shape+vml.shape

(5, 2, 3, 8, 2, 3, 4)

In [101]:
a = (1,2)
b = [1,2]
c = 1
type(c) in [tuple, list]

False

In [147]:
a = np.array([[1,2,3], [3,-1, 12]])
a

array([[ 1,  2,  3],
       [ 3, -1, 12]])

In [149]:
(a>0).sum(1)

array([3, 2])

In [157]:
np.any(a == 0 or a == 1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [177]:
min(1,2,3)

1

In [181]:
numPorts =7
cbRiRestriction = "11110110"
[r for r in range(numPorts) if cbRiRestriction[-1-r]=='1']


[1, 2, 4, 5, 6]

In [172]:
list(1)

TypeError: 'int' object is not iterable

In [280]:
h = np.transpose(np.arange(60).reshape(5,3,4),(0,2,1))
h = h+0.1j*h
h.shape, h

((5, 4, 3),
 array([[[ 0.+0.j ,  4.+0.4j,  8.+0.8j],
         [ 1.+0.1j,  5.+0.5j,  9.+0.9j],
         [ 2.+0.2j,  6.+0.6j, 10.+1.j ],
         [ 3.+0.3j,  7.+0.7j, 11.+1.1j]],
 
        [[12.+1.2j, 16.+1.6j, 20.+2.j ],
         [13.+1.3j, 17.+1.7j, 21.+2.1j],
         [14.+1.4j, 18.+1.8j, 22.+2.2j],
         [15.+1.5j, 19.+1.9j, 23.+2.3j]],
 
        [[24.+2.4j, 28.+2.8j, 32.+3.2j],
         [25.+2.5j, 29.+2.9j, 33.+3.3j],
         [26.+2.6j, 30.+3.j , 34.+3.4j],
         [27.+2.7j, 31.+3.1j, 35.+3.5j]],
 
        [[36.+3.6j, 40.+4.j , 44.+4.4j],
         [37.+3.7j, 41.+4.1j, 45.+4.5j],
         [38.+3.8j, 42.+4.2j, 46.+4.6j],
         [39.+3.9j, 43.+4.3j, 47.+4.7j]],
 
        [[48.+4.8j, 52.+5.2j, 56.+5.6j],
         [49.+4.9j, 53.+5.3j, 57.+5.7j],
         [50.+5.j , 54.+5.4j, 58.+5.8j],
         [51.+5.1j, 55.+5.5j, 59.+5.9j]]]))

In [281]:
w = np.arange(6).reshape(2,3).T
w = w +.1j*w
w.shape, w

((3, 2),
 array([[0.+0.j , 3.+0.3j],
        [1.+0.1j, 4.+0.4j],
        [2.+0.2j, 5.+0.5j]]))

In [286]:
def getSINR(h, w, noiseVar):
    # h: L x K x Nr x Nt  or n x Nr x Nt
    # w: Nt x Nl   (Note that Nl<= min(Nr,Nt))
    # Returns n x nl
    h = h.reshape(-1, h.shape[-2], h.shape[-1])          # n x Nr x Nt   (n=L*K if h is 4D)
    heff = np.matmul(h,w,axes=[(1,2),(0,1),(1,2)])       # n x Nr x Nl
    u, s, vH = np.linalg.svd(heff, full_matrices=False)  # n x Nr x Nl , n x Nl, n x Nl x Nl
    noisyInvS = 1/(np.square(s)+noiseVar)                # n x Nl
    # Calculating (V . noisyInvS . VH) is the same as:
    #  1) expanding dimensions of 'noisyInvS',  n x Nl =>                  n x Nl x 1
    #  2) calculating V.VH witch is the same square of magnitude of V      n x Nl x Nl
    #  3) doing elementwise multiplication (with boadcasting on last dim)  n x Nl x Nl
    #  4) summing on second axis                                           n x Nl
    gamma = 1/(noiseVar*(noisyInvS[:,:,None] * np.square(np.abs(vH))).sum(1)) - 1
    return gamma.real         # n x Nl

In [287]:
getSINR(h, w, 0.1234)

array([[ 37.99168153, 359.63323565],
       [  4.56863075,  71.35297339],
       [  1.70391124,  37.05619982],
       [  0.904854  ,  26.78160181],
       [  0.57413193,  22.42505049]])

In [288]:
getSINR(h, w, 0.1234)

array([[ 37.99168153, 359.63323565],
       [  4.56863075,  71.35297339],
       [  1.70391124,  37.05619982],
       [  0.904854  ,  26.78160181],
       [  0.57413193,  22.42505049]])

In [211]:
Matlab:
nVar = 0.1234;
h = reshape(0:59,4,3,5)+0.1i*reshape(0:59,4,3,5);
w = reshape(0:5,3,2)+0.1i*reshape(0:5,3,2);
r = pagemtimes(h,w);
[~, sb, vb] = pagesvd(r,"econ","vector");
size(vb)
size(sb)

a1 = (1./(sb.^2+nVar));
size(a1)
a2 = 1./(nVar*squeeze(sum(pagetranspose(a1) .* (abs(vb) .^2), 2)));
size(a2)
sinr = real(a2-1)

SyntaxError: invalid syntax (2587114578.py, line 1)

In [209]:
r = np.matmul(h,w,axes=[(1,2),(0,1),(1,2)])
r[3,:,:]

array([[ 64, 244, 424, 604, 784],
       [ 67, 256, 445, 634, 823]])

In [220]:
u, s, vH = np.linalg.svd(r, full_matrices=False)
s.shape, s, s[2,:], np.square(s)

((4, 2),
 array([[2.08694782e+02, 1.21976428e+00],
        [6.72022958e+02, 3.78794263e-01],
        [1.13746866e+03, 2.23793807e-01],
        [1.60318900e+03, 1.58782552e-01]]),
 array([1.13746866e+03, 2.23793807e-01]),
 array([[4.35535122e+04, 1.48782490e+00],
        [4.51614857e+05, 1.43485094e-01],
        [1.29383495e+06, 5.00836679e-02],
        [2.57021497e+06, 2.52118989e-02]]))

In [219]:
vH.shape, vH, vH[:,0,3]

((4, 2, 5),
 array([[[-0.07846033, -0.23394205, -0.38942377, -0.54490549,
          -0.7003872 ],
         [-0.77061273, -0.49524854, -0.21988435,  0.05547983,
           0.33084402]],
 
        [[-0.06215885, -0.22342462, -0.3846904 , -0.54595617,
          -0.70722194],
         [-0.77209862, -0.50008143, -0.22806424,  0.04395294,
           0.31597013]],
 
        [[-0.05908594, -0.22143288, -0.38377981, -0.54612675,
          -0.70847368],
         [-0.77233985, -0.50096655, -0.22959324,  0.04178007,
           0.31315338]],
 
        [[-0.0577943 , -0.22059482, -0.38339534, -0.54619585,
          -0.70899637],
         [-0.77243758, -0.50133614, -0.2302347 ,  0.04086674,
           0.31196819]]]),
 array([-0.54490549, -0.54595617, -0.54612675, -0.54619585]))

In [298]:
def myFun(*argv):
    argv = list(argv)[::-1]
    for arg in argv:
        print(arg)
myFun("shahab", "hamidi")

hamidi
shahab


In [337]:
def getCombs(*argv):
    lists = []
    for listI in argv[::-1]:
        if type(listI)==list: lists += [listI]
        else:                 lists += [list(range(listI))]
            
    lists = [lists[1]] + [lists[0]] + lists[2:]    
    n = len(lists)
    a = list(range(n-1,1,-1)) + [0,1]
    return np.array(np.meshgrid(*lists)).T.reshape(-1,n)[:,a]

combs = getCombs(3,1,[5,6],[7,8])
for i,j,p,q in combs:
    print(i,j,p,q)
combs[0][2:-1]

0 0 5 7
0 0 5 8
0 0 6 7
0 0 6 8
1 0 5 7
1 0 5 8
1 0 6 7
1 0 6 8
2 0 5 7
2 0 5 8
2 0 6 7
2 0 6 8


array([5])

In [292]:
np.meshgrid([1, 2, 3], [4, 5], [6, 7], [8,9])

[array([[[[1, 1],
          [1, 1]],
 
         [[2, 2],
          [2, 2]],
 
         [[3, 3],
          [3, 3]]],
 
 
        [[[1, 1],
          [1, 1]],
 
         [[2, 2],
          [2, 2]],
 
         [[3, 3],
          [3, 3]]]]),
 array([[[[4, 4],
          [4, 4]],
 
         [[4, 4],
          [4, 4]],
 
         [[4, 4],
          [4, 4]]],
 
 
        [[[5, 5],
          [5, 5]],
 
         [[5, 5],
          [5, 5]],
 
         [[5, 5],
          [5, 5]]]]),
 array([[[[6, 6],
          [7, 7]],
 
         [[6, 6],
          [7, 7]],
 
         [[6, 6],
          [7, 7]]],
 
 
        [[[6, 6],
          [7, 7]],
 
         [[6, 6],
          [7, 7]],
 
         [[6, 6],
          [7, 7]]]]),
 array([[[[8, 9],
          [8, 9]],
 
         [[8, 9],
          [8, 9]],
 
         [[8, 9],
          [8, 9]]],
 
 
        [[[8, 9],
          [8, 9]],
 
         [[8, 9],
          [8, 9]],
 
         [[8, 9],
          [8, 9]]]])]

In [1]:
import numpy as np
from neoradium import Carrier, AntennaElement, AntennaPanel, CsiReport


In [2]:
carrier = Carrier(startRb=0, numRbs=52, spacing=15)
bwp = carrier.curBwp

# Create an antenna panel using default antenna element template.
txAntenna = AntennaPanel([1,2], polarization="x")
# txAntenna.showElements(zeroTicks=True)
txAntenna.shape, txAntenna.getNumElements()

(array([1, 2], dtype=int16), 4)

In [3]:
for codebookType in ["Type1SP"]:
    for codebookMode in [1,2]:
        for numLayers in [1,2,3,4]:
            csiReport = CsiReport(bwp=bwp, codebookType=codebookType, codebookMode=codebookMode, txAntenna=txAntenna)
            indexes, codebook = csiReport.getCodebook(numLayers=numLayers)
            print(codebookType, "codebookMode:", codebookMode, "numLayers:", numLayers)
            print(len(indexes), "indexes, codebook Shape:", codebook.shape)


Type1SP codebookMode: 1 numLayers: 1
32 indexes, codebook Shape: (32, 4, 1)
Type1SP codebookMode: 1 numLayers: 2
32 indexes, codebook Shape: (32, 4, 2)
Type1SP codebookMode: 1 numLayers: 3
16 indexes, codebook Shape: (16, 4, 3)
Type1SP codebookMode: 1 numLayers: 4
16 indexes, codebook Shape: (16, 4, 4)
Type1SP codebookMode: 2 numLayers: 1
64 indexes, codebook Shape: (64, 4, 1)
Type1SP codebookMode: 2 numLayers: 2
128 indexes, codebook Shape: (128, 4, 2)
Type1SP codebookMode: 2 numLayers: 3
16 indexes, codebook Shape: (16, 4, 3)
Type1SP codebookMode: 2 numLayers: 4
16 indexes, codebook Shape: (16, 4, 4)


In [4]:
csiReport.n1, csiReport.n2

(2, 1)

In [5]:
a = '~'
a in [True, '~']

True